// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Kursio.Modules.Teachers.Infrastructure.Database.Migrations
{
    /// <inheritdoc />
    public partial class Create_Database : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.EnsureSchema(
                name: "teachers");

            migrationBuilder.CreateTable(
                name: "classrooms",
                schema: "teachers",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    name = table.Column<string>(type: "text", nullable: false),
                    associated_course_count = table.Column<int>(type: "integer", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_classrooms", x => x.id);
                });

            migrationBuilder.CreateTable(
                name: "students",
                schema: "teachers",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    full_name = table.Column<string>(type: "text", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_students", x => x.id);
                });

            migrationBuilder.CreateTable(
                name: "teachers",
                schema: "teachers",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    full_name = table.Column<string>(type: "text", nullable: false),
                    phone_number = table.Column<string>(type: "text", nullable: false),
                    associated_course_count = table.Column<int>(type: "integer", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_teachers", x => x.id);
                });

            migrationBuilder.CreateTable(
                name: "topics",
                schema: "teachers",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    name = table.Column<string>(type: "text", nullable: false),
                    associated_course_count = table.Column<int>(type: "integer", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_topics", x => x.id);
                });

            migrationBuilder.CreateTable(
                name: "courses",
                schema: "teachers",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    day_of_week = table.Column<int>(type: "integer", nullable: false),
                    start_time = table.Column<TimeSpan>(type: "interval", nullable: false),
                    duration = table.Column<TimeSpan>(type: "interval", nullable: false),
                    teacher_id = table.Column<Guid>(type: "uuid", nullable: false),
                    classroom_id = table.Column<Guid>(type: "uuid", nullable: false),
                    topic_id = table.Column<Guid>(type: "uuid", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_courses", x => x.id);
                    table.ForeignKey(
                        name: "fk_courses_classrooms_classroom_id",
                        column: x => x.classroom_id,
                        principalSchema: "teachers",
                        principalTable: "classrooms",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "fk_courses_teachers_teacher_id",
                        column: x => x.teacher_id,
                        principalSchema: "teachers",
                        principalTable: "teachers",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "fk_courses_topics_topic_id",
                        column: x => x.topic_id,
                        principalSchema: "teachers",
                        principalTable: "topics",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "course_students",
                schema: "teachers",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    student_id = table.Column<Guid>(type: "uuid", nullable: false),
                    course_id = table.Column<Guid>(type: "uuid", nullable: false),
                    payment_amount = table.Column<int>(type: "integer", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_course_students", x => x.id);
                    table.ForeignKey(
                        name: "fk_course_students_courses_course_id",
                        column: x => x.course_id,
                        principalSchema: "teachers",
                        principalTable: "courses",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "fk_course_students_students_student_id",
                        column: x => x.student_id,
                        principalSchema: "teachers",
                        principalTable: "students",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateIndex(
                name: "ix_course_students_course_id",
                schema: "teachers",
                table: "course_students",
                column: "course_id");

            migrationBuilder.CreateIndex(
                name: "ix_course_students_student_id",
                schema: "teachers",
                table: "course_students",
                column: "student_id");

            migrationBuilder.CreateIndex(
                name: "ix_courses_classroom_id",
                schema: "teachers",
                table: "courses",
                column: "classroom_id");

            migrationBuilder.CreateIndex(
                name: "ix_courses_teacher_id",
                schema: "teachers",
                table: "courses",
                column: "teacher_id");

            migrationBuilder.CreateIndex(
                name: "ix_courses_topic_id",
                schema: "teachers",
                table: "courses",
                column: "topic_id");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "course_students",
                schema: "teachers");

            migrationBuilder.DropTable(
                name: "courses",
                schema: "teachers");

            migrationBuilder.DropTable(
                name: "students",
                schema: "teachers");

            migrationBuilder.DropTable(
                name: "classrooms",
                schema: "teachers");

            migrationBuilder.DropTable(
                name: "teachers",
                schema: "teachers");

            migrationBuilder.DropTable(
                name: "topics",
                schema: "teachers");
        }
    }
}
